---
# Site
baseurl: "https://westoverstrategyinc.com"
title: "Westover Strategy, Inc."
enableRobotsTXT: true
googleAnalytics: ""
# Content
languageCode: "en-us"
defaultContentLanguage: "en"
enableMissingTranslationPlaceholders: false
paginate: 10
disableRSS: true
# Directories
archetypeDir: "archetypes"
contentDir: "content"
dataDir: "data"
layoutDir: "layouts"
# Formats
defaultExtension: "html"
metaDataFormat: "yaml"
# Params
params:
  blaupause:
    useModernizr: false
# DO NOT CHANGE BELOW THIS LINE
# -----------------------------
disableLiveReload: true
watch: false
---
