backend:
  name: github
  repo: westover-strategy/westover-strategy-website
  branch: master
media_folder: "src/images/uploads"
public_folder: "static/images/uploads"
collections:
  - name: "about" 
    label: "About" 
    folder: "hugo/content/about" 
    create: false 
    slug: "{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "contact" 
    label: "Contact" 
    folder: "hugo/content/contact" 
    create: false 
    slug: "{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "article" 
    label: "Article" 
    folder: "hugo/content/perspectives/articles" 
    create: true
    fields: 
      - {label: "Type", name: "type", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Publication URL", name: "publication_url", widget: "string"}
      - label: "Authors"
        name: "publication_authors"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
      - {label: "Remarks", name: "body", widget: "markdown"}
  - name: "book" 
    label: "Book" 
    folder: "hugo/content/perspectives/books" 
    create: true
    fields: 
      - {label: "Type", name: "type", widget: "hidden", default: "book"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Publication URL", name: "publication_url", widget: "string"}
      - label: "Authors"
        name: "publication_authors"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
      - {label: "Remarks", name: "body", widget: "markdown"}
  - name: "why" 
    label: "Why Westover" 
    folder: "hugo/content/why-westover" 
    create: false
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Features"
        name: "featureblocks"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
  - name: "work" 
    label: "Cases" 
    folder: "hugo/content/work" 
    create: true
    fields: 
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Browser Title", name: "browsertitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Client name", name: "client", widget: "string"}
      - {label: "Header image", name: "header_image", widget: "image"}
      - {label: "Header image width", name: "header_image_width", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        fields:
          - {label: "Quote", name: "quote", widget: "text"}
          - {label: "Who said it", name: "name", widget: "string"}
          - {label: "Job title", name: "title", widget: "string"}
          - {label: "Organization", name: "organization", widget: "string"}
