backend:
  name: github
  repo: westover-strategy/westover-strategy-website
  branch: master
media_folder: "static/images/uploads"
collections:
  - name: "about" 
    label: "About" 
    folder: "hugo/content/about" 
    create: false 
    slug: "{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
